import assert from 'node:assert/strict';
import {validateTimeline,planFromSentences,layaChoice} from '../site/failover.js';
const p=planFromSentences([{text:'A full sentence.',start:1,end:6},{text:'Another.',start:8,end:13}],45);
assert.equal(validateTimeline(p,20).seconds,45);
assert.equal(p.segments.reduce((n,s)=>n+s.frames,0),1350);
assert.throws(()=>validateTimeline({...p,seconds:44},20));
assert.throws(()=>validateTimeline({...p,segments:[{hold:-1,frames:1350}]},20));
assert.throws(()=>validateTimeline({...p,segments:[{start:0,end:40,frames:1350}]},20));
await assert.rejects(layaChoice('text',{a:'one'},{enabled:false}),/consent/);
await assert.rejects(layaChoice('text',{a:'one'},{enabled:true,endpoint:'http://example.com'}),/HTTPS/);
console.log('PASS: exact timelines, invalid boundaries, consent and endpoint safety');
const originalFetch=globalThis.fetch;
try {
 globalThis.fetch=async()=>new Response(JSON.stringify({answers:{selection:{choice:'invented_option',confidence:.9}}}));
 await assert.rejects(layaChoice('text',{a:'one'},{enabled:true,endpoint:'https://example.com'}),/Invalid Laya/);
 globalThis.fetch=async()=>new Response(JSON.stringify({answers:{selection:{choice:'a',confidence:.1}}}));
 assert.equal((await layaChoice('text',{a:'one'},{enabled:true,endpoint:'https://example.com'})).needsReview,true);
 globalThis.fetch=async()=>new Response('Service unavailable',{status:503});
 await assert.rejects(layaChoice('text',{a:'one'},{enabled:true,endpoint:'https://example.com'}),/503/);
 console.log('PASS: injected invalid Laya answer, confidence gate, and server failure');
} finally {globalThis.fetch=originalFetch;}
const {NODES,order,edges,layout}=await import('../site/pipeline/graph.js');
const {runPipeline}=await import('../site/pipeline/engine.js');
const {createStatus}=await import('../site/ui/status.js');
assert.deepEqual(order().map(n=>n.id),['source','voz','ear','uhm','align','clips','laya','clear','review','export']);
assert.throws(()=>order([{id:'a',deps:['b']},{id:'b',deps:['a']}]),/cycle/);
assert.throws(()=>order([{id:'a',deps:['missing']}]),/unknown/);
assert.ok(edges().some(e=>e.from==='clips'&&e.to==='laya'&&e.failover));
const {pos}=layout();for(const n of NODES)for(const d of n.deps)assert.ok(pos.get(d).layer<pos.get(n.id).layer);
const ran=[],skipped=[];
await runPipeline({voz:{run:()=>ran.push('voz')},laya:{when:()=>false,run:()=>ran.push('laya')},clear:{run:()=>ran.push('clear')}},{},{onSkip:id=>skipped.push(id)});
assert.deepEqual(ran,['voz','clear']);assert.deepEqual(skipped,['laya']);
const halted=new AbortController();halted.abort();
await assert.rejects(runPipeline({voz:{run:()=>{}}},{signal:halted.signal}),e=>e.name==='AbortError');
const st=createStatus();st.push({stage:'clips',status:'failed',detail:'x'});st.push({stage:'Laya',status:'needs review',detail:'y'});st.push({stage:'clips',status:'fallback',detail:'z'});
assert.equal(st.get('clips').tone,'fallback');assert.equal(st.get('clips').history.length,2);assert.equal(st.get('laya').tone,'review');assert.equal(st.get('export').tone,'idle');
console.log('PASS: stage graph order, layering, cycle detection, conditional steps, cancellation, status mapping');
const {ancestors,descendants,selection}=await import('../site/pipeline/graph.js');
const {move}=await import('../site/ui/sortable.js');
assert.deepEqual([...ancestors('align')].sort(),['ear','source','voz']);
assert.deepEqual([...descendants('clips')].sort(),['export','laya','review']);
assert.deepEqual([...selection('uhm','stage')],['uhm']);
assert.ok(selection('review','upstream').has('clear')&&!selection('review','upstream').has('export'));
assert.ok(selection('clips','downstream').has('export')&&!selection('clips','downstream').has('voz'));
assert.throws(()=>selection('nope','stage'),/Unknown stage/);assert.throws(()=>selection('voz','sideways'),/Unknown run mode/);
const log2=[];
assert.deepEqual(await runPipeline({voz:{run:()=>log2.push('voz')},ear:{run:()=>log2.push('ear')},align:{run:()=>log2.push('align')}},{},{only:selection('align','upstream')}),['voz','ear','align']);
await assert.rejects(runPipeline({clips:{needs:()=>'a transcript',run:()=>{}}},{},{only:new Set(['clips']),target:'clips'}),/Clips needs a transcript/);
await assert.rejects(runPipeline({},{},{only:new Set(['source']),target:'source'}),/cannot be run on its own/);
const forced=[];await runPipeline({laya:{when:()=>false,run:()=>forced.push('laya')}},{},{only:new Set(['laya']),target:'laya'});
assert.deepEqual(forced,['laya'],'explicitly chosen stage runs even when its condition is false');
assert.deepEqual(move(['a','b','c','d'],0,2),['b','c','a','d']);assert.deepEqual(move(['a','b','c'],2,0),['c','a','b']);assert.deepEqual(move(['a','b'],0,9),['b','a']);
console.log('PASS: graph selections, subset runs, input checks, explicit targets, reorder');
const {repairAlignment,validateWords}=await import('../site/pipeline/words.js');
{const orig=[{text:'a',start:0,end:.4},{text:'b',start:.5,end:.9},{text:'c',start:1,end:1.4},{text:'d',start:1.5,end:1.9}];
 const r=repairAlignment(orig,[{start:.02,end:.4},{start:1.2,end:1.3},{start:1.05,end:1.4},{start:1.55,end:1.9,refined:false}],10);
 assert.deepEqual(r.words.map(w=>w.refined),[true,false,true,false]);assert.equal(r.kept,2);assert.equal(r.words[1].start,.5);
 assert.doesNotThrow(()=>validateWords(r.words,10));
 const crossed=repairAlignment(orig,[{start:0,end:.4},{start:2,end:2.1},{start:.6,end:.7},{start:.65,end:.8}],10);
 assert.doesNotThrow(()=>validateWords(crossed.words,10),'cascading conflicts settle into order');
 assert.equal(repairAlignment(orig,orig.map(w=>({...w,start:NaN})),10).kept,0);
 assert.throws(()=>repairAlignment(orig,orig.slice(1),10),/3 words for 4/);
 for(let t=0;t<200;t++){const o=Array.from({length:30},(_,i)=>({text:'w'+i,start:i,end:i+.8})),a=o.map(w=>({start:w.start+(Math.random()*4-2),end:w.end+(Math.random()*4-2)}));assert.doesNotThrow(()=>validateWords(repairAlignment(o,a,40).words,40));}}
console.log('PASS: Align repair keeps ordered refinements, reverts only conflicts (200 randomized cases)');
