import {chromium} from 'playwright';import fs from 'node:fs';import http from 'node:http';import path from 'node:path';import {execFileSync} from 'node:child_process';
const root=path.resolve(new URL('../site/',import.meta.url).pathname),out=path.resolve('test-output');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const f=path.join(root,new URL(req.url,'http://localhost').pathname.replace(/\/$/,'/index.html'));if(!f.startsWith(root+path.sep)||!fs.existsSync(f)){res.writeHead(404).end();return;}const ext=path.extname(f);res.setHeader('Content-Type',ext==='.js'?'text/javascript':ext==='.html'?'text/html':ext==='.json'?'application/json':ext==='.mp4'?'video/mp4':'application/octet-stream');fs.createReadStream(f).pipe(res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--autoplay-policy=no-user-gesture-required','--disk-cache-size=1']}),page=await browser.newPage({acceptDownloads:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 for(const [name,duration] of [['voiceover-test-tone',2],['oversized-tone',6]])execFileSync('ffmpeg',['-v','error','-y','-f','lavfi','-i',`sine=frequency=440:duration=${duration}`,'-ar','48000',`${out}/${name}.wav`]);
 await page.goto(`http://127.0.0.1:${server.address().port}/`);await page.locator('[data-example="1b"]').click();await page.waitForFunction(()=>document.querySelector('#timeline').value.includes('"seconds": 120'),null,{timeout:60000});
 await page.locator('#voice').setInputFiles(`${out}/oversized-tone.wav`);await page.waitForFunction(()=>document.querySelector('#voice-status').textContent.includes('Trim and re-import'),null,{timeout:10000});
 await page.locator('#voice').setInputFiles(`${out}/voiceover-test-tone.wav`);await page.waitForFunction(()=>document.querySelector('#voice-status').textContent.includes('attached'),null,{timeout:10000});
 await page.locator('#export').click();await page.waitForFunction(()=>window.lastExport||document.querySelector('#status').textContent.includes('needs attention'),null,{timeout:300000});const result=await page.evaluate(()=>window.lastExport);if(!result)throw Error(await page.locator('#status').textContent());
 const d=page.waitForEvent('download');await page.locator('#downloads a').click();const download=await d;const file=`${out}/browser-export-120s-voice-test.mp4`;await download.saveAs(file);
 const meta=JSON.parse(execFileSync('ffprobe',['-v','error','-count_frames','-show_streams','-show_format','-of','json',file]));const v=meta.streams.find(s=>s.codec_type==='video');if(Number(meta.format.duration)!==120||Number(v.nb_read_frames)!==3600)throw Error('Wrong exact length');
 const pcm=execFileSync('ffmpeg',['-v','error','-i',file,'-t','4','-ac','1','-ar','48000','-f','f32le','pipe:1']);const samples=new Float32Array(pcm.buffer,pcm.byteOffset,pcm.byteLength/4);let peak=0,silent=0;for(let i=4800;i<72000;i++)peak=Math.max(peak,Math.abs(samples[i]));for(let i=144000;i<180000;i++)silent=Math.max(silent,Math.abs(samples[i]));if(peak<.05||silent>.0001)throw Error(`Bad voice-over splice: ${peak}/${silent}`);
 const report={exactSeconds:120,frames:3600,width:v.width,height:v.height,oversizedVoiceRejected:true,voiceoverSplicePeak:peak,remainingSlotSilencePeak:silent,errors};fs.writeFileSync(`${root}/voiceover-browser-verification.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}finally{await browser.close();await new Promise(r=>server.close(r));}

